// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_PowerON.h"
#include "screens/ui_MainScreen.h"
#include "screens/ui_SolderingTempSetScreen.h"
#include "screens/ui_SystemSettingScreen.h"
#include "screens/ui_HeatgunTempSetScreen.h"
#include "screens/ui_PIDSettingScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Start_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_739362403);    // assets/开机头图.png
LV_IMG_DECLARE(ui_img_1671917170);    // assets/material-symbols_settings-rounded.png
LV_IMG_DECLARE(ui_img_185202102);    // assets/material-symbols_volume-off-outline-rounded.png
LV_IMG_DECLARE(ui_img_1699618864);    // assets/material-symbols_volume-up-outline-rounded.png
LV_IMG_DECLARE(ui_img_1708415670);    // assets/material-symbols_mode-fan-off-outline-sharp.png
LV_IMG_DECLARE(ui_img_2103744591);    // assets/material-symbols_mode-fan-outline.png
LV_IMG_DECLARE(ui_img_740489818);    // assets/material-symbols_thermostat-rounded.png
LV_IMG_DECLARE(ui_img_1249241237);    // assets/icon-park-solid_sleep.png
LV_IMG_DECLARE(ui_img_1357884022);    // assets/material-symbols_looks-one-rounded.png
LV_IMG_DECLARE(ui_img_155116563);    // assets/material-symbols_instant-mix-rounded.png
LV_IMG_DECLARE(ui_img_1347724781);    // assets/material-symbols_play-arrow-rounded.png
LV_IMG_DECLARE(ui_img_413634367);    // assets/material-symbols_stop-rounded.png
LV_IMG_DECLARE(ui_img_2126869900);    // assets/material-symbols_looks-two-rounded.png
LV_IMG_DECLARE(ui_img_938671949);    // assets/material-symbols_check-rounded.png
LV_IMG_DECLARE(ui_img_13634893);    // assets/material-symbols_close-rounded.png
LV_IMG_DECLARE(ui_img_num0_png);    // assets/Num0.png
LV_IMG_DECLARE(ui_img_num1_png);    // assets/Num1.png
LV_IMG_DECLARE(ui_img_num2_png);    // assets/Num2.png
LV_IMG_DECLARE(ui_img_num3_png);    // assets/Num3.png
LV_IMG_DECLARE(ui_img_num4_png);    // assets/Num4.png
LV_IMG_DECLARE(ui_img_num5_png);    // assets/Num5.png
LV_IMG_DECLARE(ui_img_num6_png);    // assets/Num6.png
LV_IMG_DECLARE(ui_img_num7_png);    // assets/Num7.png
LV_IMG_DECLARE(ui_img_num8_png);    // assets/Num8.png
LV_IMG_DECLARE(ui_img_num9_png);    // assets/Num9.png
LV_IMG_DECLARE(ui_img_852573520);    // assets/material-symbols_chevron-left-rounded.png
LV_IMG_DECLARE(ui_img_637286161);    // assets/material-symbols_backlight-high-rounded.png
LV_IMG_DECLARE(ui_img_1723942165);    // assets/material-symbols_save-outline-rounded.png
LV_IMG_DECLARE(ui_img_minus_png);    // assets/minus.png
LV_IMG_DECLARE(ui_img_plus_png);    // assets/plus.png
LV_IMG_DECLARE(ui_img_295618317);    // assets/material-symbols_avg-pace-rounded.png
LV_IMG_DECLARE(ui_img_817906860);    // assets/material-symbols_fitbit-arrow-downward-rounded.png
LV_IMG_DECLARE(ui_img_1345483443);    // assets/material-symbols_fitbit-arrow-upward-rounded.png
LV_IMG_DECLARE(ui_img_1956478733);    // assets/material-symbols_heat.png
LV_IMG_DECLARE(ui_img_1162706898);    // assets/material-symbols_mode-fan-outline-sharp.png
LV_IMG_DECLARE(ui_img_921610142);    // assets/material-symbols_screen-share-outline-rounded.png
LV_IMG_DECLARE(ui_img_290686881);    // assets/material-symbols_search-activity-rounded.png
LV_IMG_DECLARE(ui_img_329106951);    // assets/material-symbols_speed-outline-rounded.png
LV_IMG_DECLARE(ui_img_1205510230);    // assets/material-symbols_storage-rounded.png

// FONTS
LV_FONT_DECLARE(ui_font_ASCII);
LV_FONT_DECLARE(ui_font_ASCII19);
LV_FONT_DECLARE(ui_font_ASCII24);
LV_FONT_DECLARE(ui_font_ASCII32);
LV_FONT_DECLARE(ui_font_ASCII48);
LV_FONT_DECLARE(ui_font_ASCII88);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
