// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void Start_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_PowerON
void ui_PowerON_screen_init(void);
extern lv_obj_t *ui_PowerON;
extern lv_obj_t *ui_ImagePowerON;
extern lv_obj_t *ui_InitializeStatusBar;
extern lv_obj_t *ui_InitializeStatus;
extern lv_obj_t *ui_FWVersion;
// CUSTOM VARIABLES

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
void ui_event_Setting( lv_event_t * e);
extern lv_obj_t *ui_Setting;
void ui_event_Buzzer( lv_event_t * e);
extern lv_obj_t *ui_Buzzer;
void ui_event_CoolingFan( lv_event_t * e);
extern lv_obj_t *ui_CoolingFan;
extern lv_obj_t *ui_TMP102Dock;
extern lv_obj_t *ui_TMP102Temp;
extern lv_obj_t *ui_ImageTMP102Temp;
extern lv_obj_t *ui_INA226Voltage;
extern lv_obj_t *ui_INA226Current;
extern lv_obj_t *ui_INA226Power;
extern lv_obj_t *ui_SystemStatusDock;
extern lv_obj_t *ui_BuzzerStatus;
extern lv_obj_t *ui_SleepStatus;
extern lv_obj_t *ui_CoolingStatus;
extern lv_obj_t *ui_Soldering;
extern lv_obj_t *ui_TextSoldering;
extern lv_obj_t *ui_ImageSoldering;
extern lv_obj_t *ui_SolderingDock;
extern lv_obj_t *ui_SolderingTempDock;
extern lv_obj_t *ui_BarSolderingDuty;
extern lv_obj_t *ui_SolderingTemp;
extern lv_obj_t *ui_TextSolderingTemp;
extern lv_obj_t *ui_SolderingSettingDock;
extern lv_obj_t *ui_TextSolderingTragetTemp;
extern lv_obj_t *ui_SolderingTargetTemp;
void ui_event_SolderingSet( lv_event_t * e);
extern lv_obj_t *ui_SolderingSet;
void ui_event_SolderingSwitch( lv_event_t * e);
extern lv_obj_t *ui_SolderingSwitch;
extern lv_obj_t *ui_Heatgun;
extern lv_obj_t *ui_TextHeatgun;
extern lv_obj_t *ui_ImageHeatgun;
extern lv_obj_t *ui_HeatgunDock;
extern lv_obj_t *ui_HeatgunTempDock;
extern lv_obj_t *ui_BarHeatgunDuty;
extern lv_obj_t *ui_HeatgunTemp;
extern lv_obj_t *ui_TextHeatgunTemp;
extern lv_obj_t *ui_HeatgunSettingDock;
extern lv_obj_t *ui_TextHeatgunTargetTemp;
extern lv_obj_t *ui_HeatgunTargetTemp;
extern lv_obj_t *ui_TextHeatgunWindSpeed;
extern lv_obj_t *ui_HeatgunWindSpeed;
void ui_event_HeatgunSet( lv_event_t * e);
extern lv_obj_t *ui_HeatgunSet;
void ui_event_HeatgunSwitch( lv_event_t * e);
extern lv_obj_t *ui_HeatgunSwitch;
// CUSTOM VARIABLES

// SCREEN: ui_SolderingTempSetScreen
void ui_SolderingTempSetScreen_screen_init(void);
extern lv_obj_t *ui_SolderingTempSetScreen;
extern lv_obj_t *ui_SolderingKeyboard;
void ui_event_SolderingConfirm( lv_event_t * e);
extern lv_obj_t *ui_SolderingConfirm;
void ui_event_SolderingDelete( lv_event_t * e);
extern lv_obj_t *ui_SolderingDelete;
void ui_event_SolderingNum0( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum0;
extern lv_obj_t *ui_SolderingNumPanel;
void ui_event_SolderingNum1( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum1;
void ui_event_SolderingNum2( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum2;
void ui_event_SolderingNum3( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum3;
void ui_event_SolderingNum4( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum4;
void ui_event_SolderingNum5( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum5;
void ui_event_SolderingNum6( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum6;
void ui_event_SolderingNum7( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum7;
void ui_event_SolderingNum8( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum8;
void ui_event_SolderingNum9( lv_event_t * e);
extern lv_obj_t *ui_SolderingNum9;
extern lv_obj_t *ui_SolderingTempSetDock;
extern lv_obj_t *ui_TextSolderingTempSetting;
extern lv_obj_t *ui_SolderingTempSetting;
extern lv_obj_t *ui_SolderingSetTemp;
extern lv_obj_t *ui_TextSolderingCurrentTemp;
extern lv_obj_t *ui_SolderingCurrentTemp;
void ui_event_SolderingTempSetBack( lv_event_t * e);
extern lv_obj_t *ui_SolderingTempSetBack;
// CUSTOM VARIABLES

// SCREEN: ui_SystemSettingScreen
void ui_SystemSettingScreen_screen_init(void);
extern lv_obj_t *ui_SystemSettingScreen;
extern lv_obj_t *ui_SystemSettingDock;
extern lv_obj_t *ui_TextSystemSetting;
void ui_event_SystemSettingBack( lv_event_t * e);
extern lv_obj_t *ui_SystemSettingBack;
extern lv_obj_t *ui_SystemSetting;
void ui_event_PIDSetting( lv_event_t * e);
extern lv_obj_t *ui_PIDSetting;
extern lv_obj_t *ui_TextPIDSetting;
void ui_event_SolderingMaxTemp( lv_event_t * e);
extern lv_obj_t *ui_SolderingMaxTemp;
extern lv_obj_t *ui_TextSolderingMaxTemp;
extern lv_obj_t *ui_NameSolderingMaxTemp;
void ui_event_SolderingMinTemp( lv_event_t * e);
extern lv_obj_t *ui_SolderingMinTemp;
extern lv_obj_t *ui_TextSolderingMinTemp;
extern lv_obj_t *ui_NameSolderingMinTemp;
void ui_event_SolderingStandbyTemp( lv_event_t * e);
extern lv_obj_t *ui_SolderingStandbyTemp;
extern lv_obj_t *ui_TextSolderingStandbyTemp;
extern lv_obj_t *ui_NameSolderingStandbyTemp;
void ui_event_SolderingStandbyTime( lv_event_t * e);
extern lv_obj_t *ui_SolderingStandbyTime;
extern lv_obj_t *ui_TextSolderingStandbyTime;
extern lv_obj_t *ui_NameSolderingStandbyTime;
void ui_event_HeatgunMaxTemp( lv_event_t * e);
extern lv_obj_t *ui_HeatgunMaxTemp;
extern lv_obj_t *ui_TextHeatgunMaxTemp;
extern lv_obj_t *ui_NameHeatgunMaxTemp;
void ui_event_HeatgunMinTemp( lv_event_t * e);
extern lv_obj_t *ui_HeatgunMinTemp;
extern lv_obj_t *ui_TextHeatgunMinTemp;
extern lv_obj_t *ui_NameHeatgunMinTemp;
void ui_event_SystemBrightness( lv_event_t * e);
extern lv_obj_t *ui_SystemBrightness;
extern lv_obj_t *ui_ImageBrightness;
extern lv_obj_t *ui_TextBrightness;
void ui_event_SettingSave( lv_event_t * e);
extern lv_obj_t *ui_SettingSave;
// CUSTOM VARIABLES

// SCREEN: ui_HeatgunTempSetScreen
void ui_HeatgunTempSetScreen_screen_init(void);
extern lv_obj_t *ui_HeatgunTempSetScreen;
extern lv_obj_t *ui_HeatgunKeyboard;
void ui_event_HeatgunConfirm( lv_event_t * e);
extern lv_obj_t *ui_HeatgunConfirm;
void ui_event_HeatgunDelete( lv_event_t * e);
extern lv_obj_t *ui_HeatgunDelete;
void ui_event_HeatgunNum0( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum0;
extern lv_obj_t *ui_HeatgunNumPanel;
void ui_event_HeatgunNum1( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum1;
void ui_event_HeatgunNum2( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum2;
void ui_event_HeatgunNum3( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum3;
void ui_event_HeatgunNum4( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum4;
void ui_event_HeatgunNum5( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum5;
void ui_event_HeatgunNum6( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum6;
void ui_event_HeatgunNum7( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum7;
void ui_event_HeatgunNum8( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum8;
void ui_event_HeatgunNum9( lv_event_t * e);
extern lv_obj_t *ui_HeatgunNum9;
extern lv_obj_t *ui_HeatgunSetDock;
extern lv_obj_t *ui_TextHeatgunSetting;
extern lv_obj_t *ui_HeatgunSetting;
void ui_event_HeatgunSetTemp( lv_event_t * e);
extern lv_obj_t *ui_HeatgunSetTemp;
extern lv_obj_t *ui_TextHeatgunCurrentTemp;
extern lv_obj_t *ui_HeatgunCurrentTemp;
void ui_event_HeatgunSetWindSpeed( lv_event_t * e);
extern lv_obj_t *ui_HeatgunSetWindSpeed;
extern lv_obj_t *ui_TextHeatgunCurrentWindSpeed;
extern lv_obj_t *ui_HeatgunCurrentWindSpeed;
void ui_event_HeatgunSetBack( lv_event_t * e);
extern lv_obj_t *ui_HeatgunSetBack;
// CUSTOM VARIABLES

// SCREEN: ui_PIDSettingScreen
void ui_PIDSettingScreen_screen_init(void);
extern lv_obj_t *ui_PIDSettingScreen;
extern lv_obj_t *ui_PIDSettingHeader;
extern lv_obj_t *ui_TextPIDSettingHeader;
void ui_event_PIDSettingBack( lv_event_t * e);
extern lv_obj_t *ui_PIDSettingBack;
extern lv_obj_t *ui_PIDSettingDock;
extern lv_obj_t *ui_TextSolderingPID;
void ui_event_SolderingKP( lv_event_t * e);
extern lv_obj_t *ui_SolderingKP;
extern lv_obj_t *ui_TextPIDKP;
void ui_event_SolderingKI( lv_event_t * e);
extern lv_obj_t *ui_SolderingKI;
extern lv_obj_t *ui_TextPIDKI;
void ui_event_SolderingKD( lv_event_t * e);
extern lv_obj_t *ui_SolderingKD;
extern lv_obj_t *ui_TextPIDKD;
void ui_event_SolderingKPDown( lv_event_t * e);
extern lv_obj_t *ui_SolderingKPDown;
void ui_event_SolderingKPUp( lv_event_t * e);
extern lv_obj_t *ui_SolderingKPUp;
void ui_event_SolderingKIDown( lv_event_t * e);
extern lv_obj_t *ui_SolderingKIDown;
void ui_event_SolderingKIUp( lv_event_t * e);
extern lv_obj_t *ui_SolderingKIUp;
void ui_event_SolderingKDDown( lv_event_t * e);
extern lv_obj_t *ui_SolderingKDDown;
void ui_event_SolderingKDUp( lv_event_t * e);
extern lv_obj_t *ui_SolderingKDUp;
extern lv_obj_t *ui_TextHeatgunPID;
void ui_event_HeatgunKP( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKP;
extern lv_obj_t *ui_TextPIDKP2;
void ui_event_HeatgunKI( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKI;
extern lv_obj_t *ui_TextPIDKI2;
void ui_event_HeatgunKD( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKD;
extern lv_obj_t *ui_TextPIDKD2;
void ui_event_HeatgunKPDown( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKPDown;
void ui_event_HeatgunKPUp( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKPUp;
void ui_event_HeatgunKIDown( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKIDown;
void ui_event_HeatgunKIUp( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKIUp;
void ui_event_HeatgunKDDown( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKDDown;
void ui_event_HeatgunKDUp( lv_event_t * e);
extern lv_obj_t *ui_HeatgunKDUp;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_739362403);   // assets/开机头图.png
LV_IMG_DECLARE( ui_img_1671917170);   // assets/material-symbols_settings-rounded.png
LV_IMG_DECLARE( ui_img_185202102);   // assets/material-symbols_volume-off-outline-rounded.png
LV_IMG_DECLARE( ui_img_1699618864);   // assets/material-symbols_volume-up-outline-rounded.png
LV_IMG_DECLARE( ui_img_1708415670);   // assets/material-symbols_mode-fan-off-outline-sharp.png
LV_IMG_DECLARE( ui_img_2103744591);   // assets/material-symbols_mode-fan-outline.png
LV_IMG_DECLARE( ui_img_740489818);   // assets/material-symbols_thermostat-rounded.png
LV_IMG_DECLARE( ui_img_1249241237);   // assets/icon-park-solid_sleep.png
LV_IMG_DECLARE( ui_img_1357884022);   // assets/material-symbols_looks-one-rounded.png
LV_IMG_DECLARE( ui_img_155116563);   // assets/material-symbols_instant-mix-rounded.png
LV_IMG_DECLARE( ui_img_1347724781);   // assets/material-symbols_play-arrow-rounded.png
LV_IMG_DECLARE( ui_img_413634367);   // assets/material-symbols_stop-rounded.png
LV_IMG_DECLARE( ui_img_2126869900);   // assets/material-symbols_looks-two-rounded.png
LV_IMG_DECLARE( ui_img_938671949);   // assets/material-symbols_check-rounded.png
LV_IMG_DECLARE( ui_img_13634893);   // assets/material-symbols_close-rounded.png
LV_IMG_DECLARE( ui_img_num0_png);   // assets/Num0.png
LV_IMG_DECLARE( ui_img_num1_png);   // assets/Num1.png
LV_IMG_DECLARE( ui_img_num2_png);   // assets/Num2.png
LV_IMG_DECLARE( ui_img_num3_png);   // assets/Num3.png
LV_IMG_DECLARE( ui_img_num4_png);   // assets/Num4.png
LV_IMG_DECLARE( ui_img_num5_png);   // assets/Num5.png
LV_IMG_DECLARE( ui_img_num6_png);   // assets/Num6.png
LV_IMG_DECLARE( ui_img_num7_png);   // assets/Num7.png
LV_IMG_DECLARE( ui_img_num8_png);   // assets/Num8.png
LV_IMG_DECLARE( ui_img_num9_png);   // assets/Num9.png
LV_IMG_DECLARE( ui_img_852573520);   // assets/material-symbols_chevron-left-rounded.png
LV_IMG_DECLARE( ui_img_637286161);   // assets/material-symbols_backlight-high-rounded.png
LV_IMG_DECLARE( ui_img_1723942165);   // assets/material-symbols_save-outline-rounded.png
LV_IMG_DECLARE( ui_img_minus_png);   // assets/minus.png
LV_IMG_DECLARE( ui_img_plus_png);   // assets/plus.png
LV_IMG_DECLARE( ui_img_295618317);   // assets/material-symbols_avg-pace-rounded.png
LV_IMG_DECLARE( ui_img_817906860);   // assets/material-symbols_fitbit-arrow-downward-rounded.png
LV_IMG_DECLARE( ui_img_1345483443);   // assets/material-symbols_fitbit-arrow-upward-rounded.png
LV_IMG_DECLARE( ui_img_1956478733);   // assets/material-symbols_heat.png
LV_IMG_DECLARE( ui_img_1162706898);   // assets/material-symbols_mode-fan-outline-sharp.png
LV_IMG_DECLARE( ui_img_921610142);   // assets/material-symbols_screen-share-outline-rounded.png
LV_IMG_DECLARE( ui_img_290686881);   // assets/material-symbols_search-activity-rounded.png
LV_IMG_DECLARE( ui_img_329106951);   // assets/material-symbols_speed-outline-rounded.png
LV_IMG_DECLARE( ui_img_1205510230);   // assets/material-symbols_storage-rounded.png

// FONTS
LV_FONT_DECLARE( ui_font_ASCII);
LV_FONT_DECLARE( ui_font_ASCII19);
LV_FONT_DECLARE( ui_font_ASCII24);
LV_FONT_DECLARE( ui_font_ASCII32);
LV_FONT_DECLARE( ui_font_ASCII48);
LV_FONT_DECLARE( ui_font_ASCII88);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
