// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void BuzzerOFF(lv_event_t * e)
{
	// Your code here
}

void BuzzerON(lv_event_t * e)
{
	// Your code here
}

void CoolingON(lv_event_t * e)
{
	// Your code here
}

void CoolingOFF(lv_event_t * e)
{
	// Your code here
}

void SolderingON(lv_event_t * e)
{
	// Your code here
}

void SolderingOFF(lv_event_t * e)
{
	// Your code here
}

void HeatgunON(lv_event_t * e)
{
	// Your code here
}

void HeatgunOFF(lv_event_t * e)
{
	// Your code here
}

void SaveConfig(lv_event_t * e)
{
	// Your code here
}

void HeatgunDelete(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum0(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum1(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum2(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum3(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum4(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum5(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum6(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum7(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum8(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum9(lv_event_t * e)
{
	// Your code here
}

void HeatgunSetTemp(lv_event_t * e)
{
	// Your code here
}

void HeatgunSetTempUN(lv_event_t * e)
{
	// Your code here
}

void HeatgunSetWindSpeed(lv_event_t * e)
{
	// Your code here
}

void HeatgunSetWindSpeedUN(lv_event_t * e)
{
	// Your code here
}

void SolderingKpUpdate(lv_event_t * e)
{
	// Your code here
}

void SolderingKiUpdate(lv_event_t * e)
{
	// Your code here
}

void SolderingKdUpdate(lv_event_t * e)
{
	// Your code here
}

void SolderingKPDown(lv_event_t * e)
{
	// Your code here
}

void SolderingKPUp(lv_event_t * e)
{
	// Your code here
}

void SolderingKIDown(lv_event_t * e)
{
	// Your code here
}

void SolderingKIUp(lv_event_t * e)
{
	// Your code here
}

void SolderingKDDown(lv_event_t * e)
{
	// Your code here
}

void SolderingKDUp(lv_event_t * e)
{
	// Your code here
}

void HeatgunKpUpdate(lv_event_t * e)
{
	// Your code here
}

void HeatgunKiUpdate(lv_event_t * e)
{
	// Your code here
}

void HeatgunKdUpdate(lv_event_t * e)
{
	// Your code here
}

void HeatgunKPDown(lv_event_t * e)
{
	// Your code here
}

void HeatgunKPUp(lv_event_t * e)
{
	// Your code here
}

void HeatgunKIDown(lv_event_t * e)
{
	// Your code here
}

void HeatgunKIUp(lv_event_t * e)
{
	// Your code here
}

void HeatgunKDDown(lv_event_t * e)
{
	// Your code here
}

void HeatgunKDUp(lv_event_t * e)
{
	// Your code here
}
