// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_TextAndImage[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_TextAndImage[1] = {255};

const ui_theme_variable_t _ui_theme_color_Container[1] = {0x393939};
const ui_theme_variable_t _ui_theme_alpha_Container[1] = {255};

const ui_theme_variable_t _ui_theme_color_ButtonAndBack[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_ButtonAndBack[1] = {255};

const ui_theme_variable_t _ui_theme_color_ButtonPressed[1] = {0x00FF8C};
const ui_theme_variable_t _ui_theme_alpha_ButtonPressed[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

