// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_HeatgunTempSetScreen_screen_init(void)
{
ui_HeatgunTempSetScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HeatgunTempSetScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeatgunTempSetScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunTempSetScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunKeyboard = lv_obj_create(ui_HeatgunTempSetScreen);
lv_obj_remove_style_all(ui_HeatgunKeyboard);
lv_obj_set_width( ui_HeatgunKeyboard, 282);
lv_obj_set_height( ui_HeatgunKeyboard, 137);
lv_obj_set_x( ui_HeatgunKeyboard, 36 );
lv_obj_set_y( ui_HeatgunKeyboard, 100 );
lv_obj_clear_flag( ui_HeatgunKeyboard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunKeyboard, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunKeyboard, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_HeatgunKeyboard, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_HeatgunConfirm = lv_btn_create(ui_HeatgunKeyboard);
lv_obj_set_width( ui_HeatgunConfirm, 77);
lv_obj_set_height( ui_HeatgunConfirm, 32);
lv_obj_set_x( ui_HeatgunConfirm, -15 );
lv_obj_set_y( ui_HeatgunConfirm, 12 );
lv_obj_set_align( ui_HeatgunConfirm, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunConfirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunConfirm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunConfirm, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunConfirm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunConfirm, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonPressed);
lv_obj_set_style_bg_img_src( ui_HeatgunConfirm, &ui_img_938671949, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunConfirm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunConfirm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunDelete = lv_btn_create(ui_HeatgunKeyboard);
lv_obj_set_width( ui_HeatgunDelete, 76);
lv_obj_set_height( ui_HeatgunDelete, 32);
lv_obj_set_x( ui_HeatgunDelete, -15 );
lv_obj_set_y( ui_HeatgunDelete, 52 );
lv_obj_set_align( ui_HeatgunDelete, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunDelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunDelete, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunDelete, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunDelete, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunDelete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunDelete, &ui_img_13634893, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunDelete, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunDelete, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunNum0 = lv_btn_create(ui_HeatgunKeyboard);
lv_obj_set_width( ui_HeatgunNum0, 76);
lv_obj_set_height( ui_HeatgunNum0, 32);
lv_obj_set_x( ui_HeatgunNum0, -15 );
lv_obj_set_y( ui_HeatgunNum0, 92 );
lv_obj_set_align( ui_HeatgunNum0, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunNum0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum0, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum0, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum0, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum0, &ui_img_num0_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum0, &ui_img_num0_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum0, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum0, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNumPanel = lv_obj_create(ui_HeatgunKeyboard);
lv_obj_set_width( ui_HeatgunNumPanel, 190);
lv_obj_set_height( ui_HeatgunNumPanel, 136);
lv_obj_set_flex_flow(ui_HeatgunNumPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_HeatgunNumPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_HeatgunNumPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HeatgunNumPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunNumPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeatgunNumPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeatgunNumPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunNum1 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum1, 48);
lv_obj_set_height( ui_HeatgunNum1, 32);
lv_obj_set_x( ui_HeatgunNum1, -20 );
lv_obj_set_y( ui_HeatgunNum1, -6 );
lv_obj_set_align( ui_HeatgunNum1, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_HeatgunNum1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HeatgunNum1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_HeatgunNum1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum1, &ui_img_num1_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum1, &ui_img_num1_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum1, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum1, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum2 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum2, 48);
lv_obj_set_height( ui_HeatgunNum2, 32);
lv_obj_set_x( ui_HeatgunNum2, -216 );
lv_obj_set_y( ui_HeatgunNum2, 7 );
lv_obj_set_align( ui_HeatgunNum2, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_HeatgunNum2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HeatgunNum2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_HeatgunNum2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum2, &ui_img_num2_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum2, &ui_img_num2_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum2, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum2, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum3 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum3, 48);
lv_obj_set_height( ui_HeatgunNum3, 32);
lv_obj_set_x( ui_HeatgunNum3, -151 );
lv_obj_set_y( ui_HeatgunNum3, 2 );
lv_obj_set_align( ui_HeatgunNum3, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_HeatgunNum3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HeatgunNum3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_HeatgunNum3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum3, &ui_img_num3_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum3, &ui_img_num3_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum3, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum3, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum4 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum4, 48);
lv_obj_set_height( ui_HeatgunNum4, 32);
lv_obj_set_x( ui_HeatgunNum4, -89 );
lv_obj_set_y( ui_HeatgunNum4, 7 );
lv_obj_set_align( ui_HeatgunNum4, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_HeatgunNum4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HeatgunNum4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_HeatgunNum4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum4, &ui_img_num4_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum4, &ui_img_num4_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum4, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum4, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum5 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum5, 48);
lv_obj_set_height( ui_HeatgunNum5, 32);
lv_obj_set_x( ui_HeatgunNum5, -212 );
lv_obj_set_y( ui_HeatgunNum5, 53 );
lv_obj_set_align( ui_HeatgunNum5, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunNum5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum5, &ui_img_num5_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum5, &ui_img_num5_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum5, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum5, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum6 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum6, 48);
lv_obj_set_height( ui_HeatgunNum6, 32);
lv_obj_set_x( ui_HeatgunNum6, -153 );
lv_obj_set_y( ui_HeatgunNum6, 52 );
lv_obj_set_align( ui_HeatgunNum6, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunNum6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum6, &ui_img_num6_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum6, &ui_img_num6_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum6, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum6, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum7 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum7, 48);
lv_obj_set_height( ui_HeatgunNum7, 32);
lv_obj_set_x( ui_HeatgunNum7, -90 );
lv_obj_set_y( ui_HeatgunNum7, 54 );
lv_obj_set_align( ui_HeatgunNum7, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunNum7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum7, &ui_img_num7_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum7, &ui_img_num7_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum7, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum7, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum8 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum8, 48);
lv_obj_set_height( ui_HeatgunNum8, 32);
lv_obj_set_x( ui_HeatgunNum8, -212 );
lv_obj_set_y( ui_HeatgunNum8, 97 );
lv_obj_set_align( ui_HeatgunNum8, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunNum8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum8, &ui_img_num8_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum8, &ui_img_num8_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum8, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum8, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunNum9 = lv_btn_create(ui_HeatgunNumPanel);
lv_obj_set_width( ui_HeatgunNum9, 48);
lv_obj_set_height( ui_HeatgunNum9, 32);
lv_obj_set_x( ui_HeatgunNum9, -154 );
lv_obj_set_y( ui_HeatgunNum9, 99 );
lv_obj_set_align( ui_HeatgunNum9, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunNum9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunNum9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunNum9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatgunNum9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_HeatgunNum9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_bg_img_src( ui_HeatgunNum9, &ui_img_num9_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunNum9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunNum9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunNum9, &ui_img_num9_png, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_HeatgunNum9, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_HeatgunNum9, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_HeatgunSetDock = lv_obj_create(ui_HeatgunTempSetScreen);
lv_obj_remove_style_all(ui_HeatgunSetDock);
lv_obj_set_width( ui_HeatgunSetDock, 316);
lv_obj_set_height( ui_HeatgunSetDock, 20);
lv_obj_set_x( ui_HeatgunSetDock, 0 );
lv_obj_set_y( ui_HeatgunSetDock, 2 );
lv_obj_set_align( ui_HeatgunSetDock, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_HeatgunSetDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunSetDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunSetDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunSetDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeatgunSetting = lv_label_create(ui_HeatgunSetDock);
lv_obj_set_width( ui_TextHeatgunSetting, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatgunSetting, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatgunSetting, 0 );
lv_obj_set_y( ui_TextHeatgunSetting, -1 );
lv_obj_set_align( ui_TextHeatgunSetting, LV_ALIGN_CENTER );
lv_label_set_text(ui_TextHeatgunSetting,"热风枪参数设置");
ui_object_set_themeable_style_property(ui_TextHeatgunSetting, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeatgunSetting, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeatgunSetting, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunSetting = lv_obj_create(ui_HeatgunTempSetScreen);
lv_obj_remove_style_all(ui_HeatgunSetting);
lv_obj_set_width( ui_HeatgunSetting, 282);
lv_obj_set_height( ui_HeatgunSetting, 72);
lv_obj_set_x( ui_HeatgunSetting, 36 );
lv_obj_set_y( ui_HeatgunSetting, 25 );
lv_obj_clear_flag( ui_HeatgunSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunSetting, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunSetting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunSetting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunSetTemp = lv_label_create(ui_HeatgunSetting);
lv_obj_set_width( ui_HeatgunSetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatgunSetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatgunSetTemp, 8 );
lv_obj_set_y( ui_HeatgunSetTemp, -10 );
lv_obj_set_align( ui_HeatgunSetTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_HeatgunSetTemp,"---℃");
lv_obj_add_flag( ui_HeatgunSetTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE );   /// Flags
ui_object_set_themeable_style_property(ui_HeatgunSetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatgunSetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatgunSetTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HeatgunSetTemp, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HeatgunSetTemp, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HeatgunSetTemp, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HeatgunSetTemp, -8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeatgunSetTemp, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeatgunSetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeatgunSetTemp, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_TextHeatgunCurrentTemp = lv_label_create(ui_HeatgunSetting);
lv_obj_set_width( ui_TextHeatgunCurrentTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatgunCurrentTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatgunCurrentTemp, 8 );
lv_obj_set_y( ui_TextHeatgunCurrentTemp, 22 );
lv_obj_set_align( ui_TextHeatgunCurrentTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextHeatgunCurrentTemp,"设定温度:");
ui_object_set_themeable_style_property(ui_TextHeatgunCurrentTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeatgunCurrentTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeatgunCurrentTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunCurrentTemp = lv_label_create(ui_HeatgunSetting);
lv_obj_set_width( ui_HeatgunCurrentTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatgunCurrentTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatgunCurrentTemp, 80 );
lv_obj_set_y( ui_HeatgunCurrentTemp, 22 );
lv_obj_set_align( ui_HeatgunCurrentTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_HeatgunCurrentTemp,"000℃");
ui_object_set_themeable_style_property(ui_HeatgunCurrentTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatgunCurrentTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatgunCurrentTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunSetWindSpeed = lv_label_create(ui_HeatgunSetting);
lv_obj_set_width( ui_HeatgunSetWindSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatgunSetWindSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatgunSetWindSpeed, 170 );
lv_obj_set_y( ui_HeatgunSetWindSpeed, -8 );
lv_obj_set_align( ui_HeatgunSetWindSpeed, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_HeatgunSetWindSpeed,"---%");
lv_obj_add_flag( ui_HeatgunSetWindSpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE );   /// Flags
ui_object_set_themeable_style_property(ui_HeatgunSetWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatgunSetWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatgunSetWindSpeed, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HeatgunSetWindSpeed, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HeatgunSetWindSpeed, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HeatgunSetWindSpeed, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HeatgunSetWindSpeed, -8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeatgunSetWindSpeed, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeatgunSetWindSpeed, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeatgunSetWindSpeed, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_TextHeatgunCurrentWindSpeed = lv_label_create(ui_HeatgunSetting);
lv_obj_set_width( ui_TextHeatgunCurrentWindSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatgunCurrentWindSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatgunCurrentWindSpeed, 169 );
lv_obj_set_y( ui_TextHeatgunCurrentWindSpeed, 22 );
lv_obj_set_align( ui_TextHeatgunCurrentWindSpeed, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextHeatgunCurrentWindSpeed,"设定风速:");
ui_object_set_themeable_style_property(ui_TextHeatgunCurrentWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeatgunCurrentWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeatgunCurrentWindSpeed, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunCurrentWindSpeed = lv_label_create(ui_HeatgunSetting);
lv_obj_set_width( ui_HeatgunCurrentWindSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatgunCurrentWindSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatgunCurrentWindSpeed, 241 );
lv_obj_set_y( ui_HeatgunCurrentWindSpeed, 22 );
lv_obj_set_align( ui_HeatgunCurrentWindSpeed, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_HeatgunCurrentWindSpeed,"000%");
ui_object_set_themeable_style_property(ui_HeatgunCurrentWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatgunCurrentWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatgunCurrentWindSpeed, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunSetBack = lv_btn_create(ui_HeatgunTempSetScreen);
lv_obj_set_width( ui_HeatgunSetBack, 32);
lv_obj_set_height( ui_HeatgunSetBack, 212);
lv_obj_set_x( ui_HeatgunSetBack, -286 );
lv_obj_set_y( ui_HeatgunSetBack, 25 );
lv_obj_set_align( ui_HeatgunSetBack, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_HeatgunSetBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunSetBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunSetBack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunSetBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunSetBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunSetBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunSetBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunSetBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HeatgunConfirm, ui_event_HeatgunConfirm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunDelete, ui_event_HeatgunDelete, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum0, ui_event_HeatgunNum0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum1, ui_event_HeatgunNum1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum2, ui_event_HeatgunNum2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum3, ui_event_HeatgunNum3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum4, ui_event_HeatgunNum4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum5, ui_event_HeatgunNum5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum6, ui_event_HeatgunNum6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum7, ui_event_HeatgunNum7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum8, ui_event_HeatgunNum8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunNum9, ui_event_HeatgunNum9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunSetTemp, ui_event_HeatgunSetTemp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunSetWindSpeed, ui_event_HeatgunSetWindSpeed, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunSetBack, ui_event_HeatgunSetBack, LV_EVENT_ALL, NULL);

}
