// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_HEATGUNTEMPSETSCREEN_H
#define UI_HEATGUNTEMPSETSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HeatgunTempSetScreen
extern void ui_HeatgunTempSetScreen_screen_init(void);
extern void ui_HeatgunTempSetScreen_screen_destroy(void);
extern lv_obj_t * ui_HeatgunTempSetScreen;
extern lv_obj_t * ui_HeatgunKeyboard;
extern void ui_event_HeatgunConfirm(lv_event_t * e);
extern lv_obj_t * ui_HeatgunConfirm;
extern void ui_event_HeatgunDelete(lv_event_t * e);
extern lv_obj_t * ui_HeatgunDelete;
extern void ui_event_HeatgunNum0(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum0;
extern lv_obj_t * ui_HeatgunNumPanel;
extern void ui_event_HeatgunNum1(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum1;
extern void ui_event_HeatgunNum2(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum2;
extern void ui_event_HeatgunNum3(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum3;
extern void ui_event_HeatgunNum4(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum4;
extern void ui_event_HeatgunNum5(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum5;
extern void ui_event_HeatgunNum6(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum6;
extern void ui_event_HeatgunNum7(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum7;
extern void ui_event_HeatgunNum8(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum8;
extern void ui_event_HeatgunNum9(lv_event_t * e);
extern lv_obj_t * ui_HeatgunNum9;
extern lv_obj_t * ui_HeatgunSetDock;
extern lv_obj_t * ui_TextHeatgunSetting;
extern lv_obj_t * ui_HeatgunSetting;
extern void ui_event_HeatgunSetTemp(lv_event_t * e);
extern lv_obj_t * ui_HeatgunSetTemp;
extern lv_obj_t * ui_TextHeatgunCurrentTemp;
extern lv_obj_t * ui_HeatgunCurrentTemp;
extern void ui_event_HeatgunSetWindSpeed(lv_event_t * e);
extern lv_obj_t * ui_HeatgunSetWindSpeed;
extern lv_obj_t * ui_TextHeatgunCurrentWindSpeed;
extern lv_obj_t * ui_HeatgunCurrentWindSpeed;
extern void ui_event_HeatgunSetBack(lv_event_t * e);
extern lv_obj_t * ui_HeatgunSetBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

