// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern void ui_event_Setting(lv_event_t * e);
extern lv_obj_t * ui_Setting;
extern void ui_event_Buzzer(lv_event_t * e);
extern lv_obj_t * ui_Buzzer;
extern void ui_event_CoolingFan(lv_event_t * e);
extern lv_obj_t * ui_CoolingFan;
extern lv_obj_t * ui_TMP102Dock;
extern lv_obj_t * ui_TMP102Temp;
extern lv_obj_t * ui_ImageTMP102Temp;
extern lv_obj_t * ui_INA226Voltage;
extern lv_obj_t * ui_INA226Current;
extern lv_obj_t * ui_INA226Power;
extern lv_obj_t * ui_SystemStatusDock;
extern lv_obj_t * ui_BuzzerStatus;
extern lv_obj_t * ui_SleepStatus;
extern lv_obj_t * ui_CoolingStatus;
extern lv_obj_t * ui_Soldering;
extern lv_obj_t * ui_TextSoldering;
extern lv_obj_t * ui_ImageSoldering;
extern lv_obj_t * ui_SolderingDock;
extern lv_obj_t * ui_SolderingTempDock;
extern lv_obj_t * ui_BarSolderingDuty;
extern lv_obj_t * ui_SolderingTemp;
extern lv_obj_t * ui_TextSolderingTemp;
extern lv_obj_t * ui_SolderingSettingDock;
extern lv_obj_t * ui_TextSolderingTragetTemp;
extern lv_obj_t * ui_SolderingTargetTemp;
extern void ui_event_SolderingSet(lv_event_t * e);
extern lv_obj_t * ui_SolderingSet;
extern void ui_event_SolderingSwitch(lv_event_t * e);
extern lv_obj_t * ui_SolderingSwitch;
extern lv_obj_t * ui_Heatgun;
extern lv_obj_t * ui_TextHeatgun;
extern lv_obj_t * ui_ImageHeatgun;
extern lv_obj_t * ui_HeatgunDock;
extern lv_obj_t * ui_HeatgunTempDock;
extern lv_obj_t * ui_BarHeatgunDuty;
extern lv_obj_t * ui_HeatgunTemp;
extern lv_obj_t * ui_TextHeatgunTemp;
extern lv_obj_t * ui_HeatgunSettingDock;
extern lv_obj_t * ui_TextHeatgunTargetTemp;
extern lv_obj_t * ui_HeatgunTargetTemp;
extern lv_obj_t * ui_TextHeatgunWindSpeed;
extern lv_obj_t * ui_HeatgunWindSpeed;
extern void ui_event_HeatgunSet(lv_event_t * e);
extern lv_obj_t * ui_HeatgunSet;
extern void ui_event_HeatgunSwitch(lv_event_t * e);
extern lv_obj_t * ui_HeatgunSwitch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

