// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_Setting = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_Setting, 102);
lv_obj_set_height( ui_Setting, 44);
lv_obj_set_x( ui_Setting, -2 );
lv_obj_set_y( ui_Setting, -3 );
lv_obj_set_align( ui_Setting, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Setting, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Setting, &ui_img_1671917170, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Setting, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Setting, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Setting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buzzer = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_Buzzer, 102);
lv_obj_set_height( ui_Buzzer, 44);
lv_obj_set_x( ui_Buzzer, 2 );
lv_obj_set_y( ui_Buzzer, -3 );
lv_obj_set_align( ui_Buzzer, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_Buzzer, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Buzzer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Buzzer, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Buzzer, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buzzer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Buzzer, &ui_img_185202102, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Buzzer, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buzzer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Buzzer, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Buzzer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Buzzer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Buzzer, &ui_img_1699618864, LV_PART_MAIN | LV_STATE_CHECKED );

ui_CoolingFan = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_CoolingFan, 102);
lv_obj_set_height( ui_CoolingFan, 44);
lv_obj_set_x( ui_CoolingFan, 0 );
lv_obj_set_y( ui_CoolingFan, -3 );
lv_obj_set_align( ui_CoolingFan, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_CoolingFan, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CoolingFan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CoolingFan, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CoolingFan, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CoolingFan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_CoolingFan, &ui_img_1708415670, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_CoolingFan, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CoolingFan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CoolingFan, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_CoolingFan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_CoolingFan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_CoolingFan, &ui_img_2103744591, LV_PART_MAIN | LV_STATE_CHECKED );

ui_TMP102Dock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_TMP102Dock);
lv_obj_set_width( ui_TMP102Dock, 74);
lv_obj_set_height( ui_TMP102Dock, 20);
lv_obj_set_x( ui_TMP102Dock, 2 );
lv_obj_set_y( ui_TMP102Dock, 2 );
lv_obj_clear_flag( ui_TMP102Dock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TMP102Dock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TMP102Dock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TMP102Dock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TMP102Dock, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TMP102Dock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TMP102Dock, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TMP102Temp = lv_label_create(ui_TMP102Dock);
lv_obj_set_width( ui_TMP102Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TMP102Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TMP102Temp, 20 );
lv_obj_set_y( ui_TMP102Temp, 0 );
lv_obj_set_align( ui_TMP102Temp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TMP102Temp,"00.00℃");
ui_object_set_themeable_style_property(ui_TMP102Temp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TMP102Temp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TMP102Temp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageTMP102Temp = lv_img_create(ui_TMP102Dock);
lv_img_set_src(ui_ImageTMP102Temp, &ui_img_740489818);
lv_obj_set_width( ui_ImageTMP102Temp, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageTMP102Temp, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageTMP102Temp, -5 );
lv_obj_set_y( ui_ImageTMP102Temp, 0 );
lv_obj_set_align( ui_ImageTMP102Temp, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageTMP102Temp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageTMP102Temp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageTMP102Temp,128);

ui_INA226Voltage = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_INA226Voltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_INA226Voltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_INA226Voltage, 78 );
lv_obj_set_y( ui_INA226Voltage, -108 );
lv_obj_set_align( ui_INA226Voltage, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_INA226Voltage,"00.00V");
lv_obj_set_style_text_color(ui_INA226Voltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_INA226Voltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_INA226Voltage, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_INA226Voltage, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_INA226Voltage, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_INA226Voltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_INA226Voltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_INA226Voltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_INA226Voltage, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_INA226Voltage, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_INA226Voltage, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_INA226Voltage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_INA226Voltage, -1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_INA226Current = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_INA226Current, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_INA226Current, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_INA226Current, 136 );
lv_obj_set_y( ui_INA226Current, -108 );
lv_obj_set_align( ui_INA226Current, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_INA226Current,"0.000A");
lv_obj_set_style_text_color(ui_INA226Current, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_INA226Current, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_INA226Current, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_INA226Current, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_INA226Current, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_INA226Current, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_INA226Current, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_INA226Current, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_INA226Current, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_INA226Current, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_INA226Current, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_INA226Current, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_INA226Current, -1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_INA226Power = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_INA226Power, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_INA226Power, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_INA226Power, 194 );
lv_obj_set_y( ui_INA226Power, -108 );
lv_obj_set_align( ui_INA226Power, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_INA226Power,"000.0W");
lv_obj_set_style_text_color(ui_INA226Power, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_INA226Power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_INA226Power, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_INA226Power, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_INA226Power, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_INA226Power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_INA226Power, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_INA226Power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_INA226Power, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_INA226Power, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_INA226Power, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_INA226Power, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_INA226Power, -1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemStatusDock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_SystemStatusDock);
lv_obj_set_width( ui_SystemStatusDock, 66);
lv_obj_set_height( ui_SystemStatusDock, 20);
lv_obj_set_x( ui_SystemStatusDock, 252 );
lv_obj_set_y( ui_SystemStatusDock, 2 );
lv_obj_clear_flag( ui_SystemStatusDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SystemStatusDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SystemStatusDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemStatusDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SystemStatusDock, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SystemStatusDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SystemStatusDock, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzerStatus = lv_img_create(ui_SystemStatusDock);
lv_img_set_src(ui_BuzzerStatus, &ui_img_1699618864);
lv_obj_set_width( ui_BuzzerStatus, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_BuzzerStatus, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_BuzzerStatus, -6 );
lv_obj_set_y( ui_BuzzerStatus, 0 );
lv_obj_set_align( ui_BuzzerStatus, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_BuzzerStatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BuzzerStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BuzzerStatus,128);

ui_SleepStatus = lv_img_create(ui_SystemStatusDock);
lv_img_set_src(ui_SleepStatus, &ui_img_1249241237);
lv_obj_set_width( ui_SleepStatus, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_SleepStatus, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_SleepStatus, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SleepStatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SleepStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_SleepStatus,128);

ui_CoolingStatus = lv_img_create(ui_SystemStatusDock);
lv_img_set_src(ui_CoolingStatus, &ui_img_2103744591);
lv_obj_set_width( ui_CoolingStatus, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_CoolingStatus, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_CoolingStatus, 6 );
lv_obj_set_y( ui_CoolingStatus, 0 );
lv_obj_set_align( ui_CoolingStatus, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_CoolingStatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CoolingStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_CoolingStatus,128);

ui_Soldering = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_Soldering);
lv_obj_set_width( ui_Soldering, 156);
lv_obj_set_height( ui_Soldering, 166);
lv_obj_set_x( ui_Soldering, 2 );
lv_obj_set_y( ui_Soldering, 24 );
lv_obj_clear_flag( ui_Soldering, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Soldering, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Soldering, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Soldering, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Soldering, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Soldering, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Soldering, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextSoldering = lv_label_create(ui_Soldering);
lv_obj_set_width( ui_TextSoldering, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextSoldering, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextSoldering, 20 );
lv_obj_set_y( ui_TextSoldering, 0 );
lv_label_set_text(ui_TextSoldering,"电烙铁-C245");
lv_obj_set_style_text_color(ui_TextSoldering, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextSoldering, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextSoldering, &ui_font_ASCII19, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageSoldering = lv_img_create(ui_Soldering);
lv_img_set_src(ui_ImageSoldering, &ui_img_1357884022);
lv_obj_set_width( ui_ImageSoldering, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageSoldering, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageSoldering, -6 );
lv_obj_set_y( ui_ImageSoldering, -6 );
lv_obj_add_flag( ui_ImageSoldering, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageSoldering, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageSoldering,190);
lv_obj_set_style_radius(ui_ImageSoldering, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SolderingDock = lv_obj_create(ui_Soldering);
lv_obj_remove_style_all(ui_SolderingDock);
lv_obj_set_width( ui_SolderingDock, 156);
lv_obj_set_height( ui_SolderingDock, 142);
lv_obj_set_x( ui_SolderingDock, -1 );
lv_obj_set_y( ui_SolderingDock, 20 );
lv_obj_clear_flag( ui_SolderingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SolderingDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SolderingDock, lv_color_hex(0x31526B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SolderingDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SolderingDock, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SolderingDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SolderingDock, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SolderingTempDock = lv_obj_create(ui_SolderingDock);
lv_obj_remove_style_all(ui_SolderingTempDock);
lv_obj_set_width( ui_SolderingTempDock, 152);
lv_obj_set_height( ui_SolderingTempDock, 69);
lv_obj_set_x( ui_SolderingTempDock, 1 );
lv_obj_set_y( ui_SolderingTempDock, 1 );
lv_obj_clear_flag( ui_SolderingTempDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarSolderingDuty = lv_bar_create(ui_SolderingTempDock);
lv_bar_set_value(ui_BarSolderingDuty,10,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarSolderingDuty, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarSolderingDuty, 152);
lv_obj_set_height( ui_BarSolderingDuty, 69);
lv_obj_set_align( ui_BarSolderingDuty, LV_ALIGN_LEFT_MID );
lv_obj_set_style_radius(ui_BarSolderingDuty, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarSolderingDuty, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarSolderingDuty, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_anim_time(ui_BarSolderingDuty, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_BarSolderingDuty, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarSolderingDuty, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarSolderingDuty, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BarSolderingDuty, lv_color_hex(0x343131), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BarSolderingDuty, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BarSolderingDuty, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BarSolderingDuty, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BarSolderingDuty, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BarSolderingDuty, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_SolderingTemp = lv_label_create(ui_SolderingTempDock);
lv_obj_set_width( ui_SolderingTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SolderingTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SolderingTemp, -2 );
lv_obj_set_y( ui_SolderingTemp, -8 );
lv_label_set_text(ui_SolderingTemp,"000");
ui_object_set_themeable_style_property(ui_SolderingTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_SolderingTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_SolderingTemp, &ui_font_ASCII88, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_SolderingTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SolderingTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextSolderingTemp = lv_label_create(ui_SolderingTempDock);
lv_obj_set_width( ui_TextSolderingTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextSolderingTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextSolderingTemp, 126 );
lv_obj_set_y( ui_TextSolderingTemp, -1 );
lv_label_set_text(ui_TextSolderingTemp,"℃");
ui_object_set_themeable_style_property(ui_TextSolderingTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextSolderingTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextSolderingTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SolderingSettingDock = lv_obj_create(ui_SolderingDock);
lv_obj_remove_style_all(ui_SolderingSettingDock);
lv_obj_set_width( ui_SolderingSettingDock, 152);
lv_obj_set_height( ui_SolderingSettingDock, 67);
lv_obj_set_x( ui_SolderingSettingDock, 0 );
lv_obj_set_y( ui_SolderingSettingDock, 72 );
lv_obj_set_align( ui_SolderingSettingDock, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_SolderingSettingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SolderingSettingDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SolderingSettingDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SolderingSettingDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextSolderingTragetTemp = lv_label_create(ui_SolderingSettingDock);
lv_obj_set_width( ui_TextSolderingTragetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextSolderingTragetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextSolderingTragetTemp, 2 );
lv_obj_set_y( ui_TextSolderingTragetTemp, -44 );
lv_obj_set_align( ui_TextSolderingTragetTemp, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TextSolderingTragetTemp,"设定温度:");
ui_object_set_themeable_style_property(ui_TextSolderingTragetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextSolderingTragetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextSolderingTragetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SolderingTargetTemp = lv_label_create(ui_SolderingSettingDock);
lv_obj_set_width( ui_SolderingTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SolderingTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SolderingTargetTemp, -10 );
lv_obj_set_y( ui_SolderingTargetTemp, 1 );
lv_obj_set_align( ui_SolderingTargetTemp, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_SolderingTargetTemp,"000℃");
lv_obj_add_flag( ui_SolderingTargetTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
ui_object_set_themeable_style_property(ui_SolderingTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_SolderingTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_SolderingTargetTemp, &ui_font_ASCII32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SolderingTargetTemp, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SolderingTargetTemp, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SolderingTargetTemp, -3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SolderingTargetTemp, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SolderingTargetTemp, 5, LV_PART_MAIN| LV_STATE_EDITED);
lv_obj_set_style_bg_color(ui_SolderingTargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_EDITED );
lv_obj_set_style_bg_opa(ui_SolderingTargetTemp, 255, LV_PART_MAIN| LV_STATE_EDITED);
lv_obj_set_style_radius(ui_SolderingTargetTemp, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_SolderingTargetTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_SolderingTargetTemp, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_SolderingTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_SolderingTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_SolderingTargetTemp, 5, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_color(ui_SolderingTargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_SolderingTargetTemp, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(ui_SolderingTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(ui_SolderingTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_SolderingSet = lv_btn_create(ui_SolderingSettingDock);
lv_obj_set_width( ui_SolderingSet, 72);
lv_obj_set_height( ui_SolderingSet, 36);
lv_obj_set_x( ui_SolderingSet, -2 );
lv_obj_set_y( ui_SolderingSet, -2 );
lv_obj_set_align( ui_SolderingSet, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_SolderingSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SolderingSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SolderingSet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SolderingSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SolderingSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SolderingSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_SolderingSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SolderingSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SolderingSwitch = lv_btn_create(ui_SolderingSettingDock);
lv_obj_set_width( ui_SolderingSwitch, 72);
lv_obj_set_height( ui_SolderingSwitch, 36);
lv_obj_set_x( ui_SolderingSwitch, 2 );
lv_obj_set_y( ui_SolderingSwitch, -2 );
lv_obj_set_align( ui_SolderingSwitch, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_SolderingSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SolderingSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SolderingSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SolderingSwitch, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SolderingSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SolderingSwitch, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_SolderingSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SolderingSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SolderingSwitch, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

ui_Heatgun = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_Heatgun);
lv_obj_set_width( ui_Heatgun, 156);
lv_obj_set_height( ui_Heatgun, 166);
lv_obj_set_x( ui_Heatgun, 162 );
lv_obj_set_y( ui_Heatgun, 24 );
lv_obj_clear_flag( ui_Heatgun, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Heatgun, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Heatgun, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Heatgun, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Heatgun, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Heatgun, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Heatgun, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeatgun = lv_label_create(ui_Heatgun);
lv_obj_set_width( ui_TextHeatgun, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatgun, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatgun, 20 );
lv_obj_set_y( ui_TextHeatgun, 0 );
lv_label_set_text(ui_TextHeatgun,"热风枪-858D");
lv_label_set_recolor(ui_TextHeatgun,"true");
lv_obj_set_style_text_color(ui_TextHeatgun, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextHeatgun, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextHeatgun, &ui_font_ASCII19, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageHeatgun = lv_img_create(ui_Heatgun);
lv_img_set_src(ui_ImageHeatgun, &ui_img_2126869900);
lv_obj_set_width( ui_ImageHeatgun, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageHeatgun, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageHeatgun, -6 );
lv_obj_set_y( ui_ImageHeatgun, -6 );
lv_obj_add_flag( ui_ImageHeatgun, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageHeatgun, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageHeatgun,190);

ui_HeatgunDock = lv_obj_create(ui_Heatgun);
lv_obj_remove_style_all(ui_HeatgunDock);
lv_obj_set_width( ui_HeatgunDock, 156);
lv_obj_set_height( ui_HeatgunDock, 142);
lv_obj_set_x( ui_HeatgunDock, -1 );
lv_obj_set_y( ui_HeatgunDock, 20 );
lv_obj_clear_flag( ui_HeatgunDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunDock, lv_color_hex(0x31526B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeatgunDock, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeatgunDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HeatgunDock, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunTempDock = lv_obj_create(ui_HeatgunDock);
lv_obj_remove_style_all(ui_HeatgunTempDock);
lv_obj_set_width( ui_HeatgunTempDock, 152);
lv_obj_set_height( ui_HeatgunTempDock, 69);
lv_obj_set_x( ui_HeatgunTempDock, 1 );
lv_obj_set_y( ui_HeatgunTempDock, 1 );
lv_obj_clear_flag( ui_HeatgunTempDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarHeatgunDuty = lv_bar_create(ui_HeatgunTempDock);
lv_bar_set_value(ui_BarHeatgunDuty,10,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarHeatgunDuty, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarHeatgunDuty, 152);
lv_obj_set_height( ui_BarHeatgunDuty, 69);
lv_obj_set_align( ui_BarHeatgunDuty, LV_ALIGN_LEFT_MID );
lv_obj_set_style_radius(ui_BarHeatgunDuty, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeatgunDuty, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeatgunDuty, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_anim_time(ui_BarHeatgunDuty, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_BarHeatgunDuty, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeatgunDuty, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeatgunDuty, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BarHeatgunDuty, lv_color_hex(0x343131), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BarHeatgunDuty, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BarHeatgunDuty, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BarHeatgunDuty, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BarHeatgunDuty, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BarHeatgunDuty, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_HeatgunTemp = lv_label_create(ui_HeatgunTempDock);
lv_obj_set_width( ui_HeatgunTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatgunTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatgunTemp, -2 );
lv_obj_set_y( ui_HeatgunTemp, -8 );
lv_label_set_text(ui_HeatgunTemp,"000");
lv_obj_set_style_text_color(ui_HeatgunTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeatgunTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeatgunTemp, &ui_font_ASCII88, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_HeatgunTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeatgunTemp = lv_label_create(ui_HeatgunTempDock);
lv_obj_set_width( ui_TextHeatgunTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatgunTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatgunTemp, 126 );
lv_obj_set_y( ui_TextHeatgunTemp, -1 );
lv_label_set_text(ui_TextHeatgunTemp,"℃");
lv_obj_set_style_text_color(ui_TextHeatgunTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextHeatgunTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextHeatgunTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunSettingDock = lv_obj_create(ui_HeatgunDock);
lv_obj_remove_style_all(ui_HeatgunSettingDock);
lv_obj_set_width( ui_HeatgunSettingDock, 152);
lv_obj_set_height( ui_HeatgunSettingDock, 67);
lv_obj_set_x( ui_HeatgunSettingDock, 0 );
lv_obj_set_y( ui_HeatgunSettingDock, 72 );
lv_obj_set_align( ui_HeatgunSettingDock, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_HeatgunSettingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunSettingDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunSettingDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunSettingDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeatgunTargetTemp = lv_label_create(ui_HeatgunSettingDock);
lv_obj_set_width( ui_TextHeatgunTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatgunTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatgunTargetTemp, 2 );
lv_obj_set_y( ui_TextHeatgunTargetTemp, -44 );
lv_obj_set_align( ui_TextHeatgunTargetTemp, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TextHeatgunTargetTemp,"温度:");
ui_object_set_themeable_style_property(ui_TextHeatgunTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeatgunTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeatgunTargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunTargetTemp = lv_label_create(ui_HeatgunSettingDock);
lv_obj_set_width( ui_HeatgunTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatgunTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatgunTargetTemp, 41 );
lv_obj_set_y( ui_HeatgunTargetTemp, -45 );
lv_obj_set_align( ui_HeatgunTargetTemp, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_HeatgunTargetTemp,"000℃");
lv_obj_add_flag( ui_HeatgunTargetTemp, LV_OBJ_FLAG_CLICKABLE );   /// Flags
ui_object_set_themeable_style_property(ui_HeatgunTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatgunTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatgunTargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HeatgunTargetTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HeatgunTargetTemp, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HeatgunTargetTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HeatgunTargetTemp, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeatgunTargetTemp, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeatgunTargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeatgunTargetTemp, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_left(ui_HeatgunTargetTemp, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_right(ui_HeatgunTargetTemp, 1, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_top(ui_HeatgunTargetTemp, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_bottom(ui_HeatgunTargetTemp, -2, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_radius(ui_HeatgunTargetTemp, 5, LV_PART_MAIN| LV_STATE_EDITED);
lv_obj_set_style_bg_color(ui_HeatgunTargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_EDITED );
lv_obj_set_style_bg_opa(ui_HeatgunTargetTemp, 255, LV_PART_MAIN| LV_STATE_EDITED);
lv_obj_set_style_radius(ui_HeatgunTargetTemp, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_HeatgunTargetTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_HeatgunTargetTemp, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_HeatgunTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_HeatgunTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_HeatgunTargetTemp, 5, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_color(ui_HeatgunTargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_HeatgunTargetTemp, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(ui_HeatgunTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(ui_HeatgunTargetTemp, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_TextHeatgunWindSpeed = lv_label_create(ui_HeatgunSettingDock);
lv_obj_set_width( ui_TextHeatgunWindSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatgunWindSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatgunWindSpeed, -34 );
lv_obj_set_y( ui_TextHeatgunWindSpeed, -43 );
lv_obj_set_align( ui_TextHeatgunWindSpeed, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_TextHeatgunWindSpeed,"风速:");
ui_object_set_themeable_style_property(ui_TextHeatgunWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeatgunWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeatgunWindSpeed, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunWindSpeed = lv_label_create(ui_HeatgunSettingDock);
lv_obj_set_width( ui_HeatgunWindSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatgunWindSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatgunWindSpeed, -2 );
lv_obj_set_y( ui_HeatgunWindSpeed, -45 );
lv_obj_set_align( ui_HeatgunWindSpeed, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_HeatgunWindSpeed,"000%");
lv_obj_add_flag( ui_HeatgunWindSpeed, LV_OBJ_FLAG_CLICKABLE );   /// Flags
ui_object_set_themeable_style_property(ui_HeatgunWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatgunWindSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatgunWindSpeed, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HeatgunWindSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HeatgunWindSpeed, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HeatgunWindSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HeatgunWindSpeed, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeatgunWindSpeed, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeatgunWindSpeed, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeatgunWindSpeed, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_left(ui_HeatgunWindSpeed, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_right(ui_HeatgunWindSpeed, 1, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_top(ui_HeatgunWindSpeed, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_bottom(ui_HeatgunWindSpeed, -2, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_radius(ui_HeatgunWindSpeed, 5, LV_PART_MAIN| LV_STATE_EDITED);
lv_obj_set_style_bg_color(ui_HeatgunWindSpeed, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_EDITED );
lv_obj_set_style_bg_opa(ui_HeatgunWindSpeed, 255, LV_PART_MAIN| LV_STATE_EDITED);
lv_obj_set_style_radius(ui_HeatgunWindSpeed, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_HeatgunWindSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_HeatgunWindSpeed, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_HeatgunWindSpeed, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_HeatgunWindSpeed, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_HeatgunWindSpeed, 5, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_color(ui_HeatgunWindSpeed, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_HeatgunWindSpeed, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(ui_HeatgunWindSpeed, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(ui_HeatgunWindSpeed, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_HeatgunSet = lv_btn_create(ui_HeatgunSettingDock);
lv_obj_set_width( ui_HeatgunSet, 72);
lv_obj_set_height( ui_HeatgunSet, 36);
lv_obj_set_x( ui_HeatgunSet, 2 );
lv_obj_set_y( ui_HeatgunSet, -2 );
lv_obj_set_align( ui_HeatgunSet, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_HeatgunSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunSet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatgunSwitch = lv_btn_create(ui_HeatgunSettingDock);
lv_obj_set_width( ui_HeatgunSwitch, 72);
lv_obj_set_height( ui_HeatgunSwitch, 36);
lv_obj_set_x( ui_HeatgunSwitch, -2 );
lv_obj_set_y( ui_HeatgunSwitch, -2 );
lv_obj_set_align( ui_HeatgunSwitch, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_HeatgunSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HeatgunSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatgunSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeatgunSwitch, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeatgunSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunSwitch, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HeatgunSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeatgunSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeatgunSwitch, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Buzzer, ui_event_Buzzer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CoolingFan, ui_event_CoolingFan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SolderingSet, ui_event_SolderingSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SolderingSwitch, ui_event_SolderingSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunSet, ui_event_HeatgunSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatgunSwitch, ui_event_HeatgunSwitch, LV_EVENT_ALL, NULL);

}
