// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_PowerON_screen_init(void)
{
ui_PowerON = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PowerON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PowerON, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_PowerON, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_ImagePowerON = lv_img_create(ui_PowerON);
lv_img_set_src(ui_ImagePowerON, &ui_img_739362403);
lv_obj_set_width( ui_ImagePowerON, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_ImagePowerON, LV_SIZE_CONTENT);   /// 96
lv_obj_set_x( ui_ImagePowerON, 0 );
lv_obj_set_y( ui_ImagePowerON, 10 );
lv_obj_set_align( ui_ImagePowerON, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_ImagePowerON, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePowerON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InitializeStatusBar = lv_bar_create(ui_PowerON);
lv_obj_set_width( ui_InitializeStatusBar, 290);
lv_obj_set_height( ui_InitializeStatusBar, 32);
lv_obj_set_x( ui_InitializeStatusBar, 0 );
lv_obj_set_y( ui_InitializeStatusBar, 10 );
lv_obj_set_align( ui_InitializeStatusBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_InitializeStatusBar, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_InitializeStatusBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InitializeStatusBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InitializeStatusBar, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InitializeStatusBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_InitializeStatusBar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_InitializeStatusBar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_InitializeStatusBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_InitializeStatusBar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_InitializeStatusBar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_InitializeStatusBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_InitializeStatusBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_anim_time(ui_InitializeStatusBar, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_InitializeStatusBar, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_InitializeStatusBar, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InitializeStatusBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_InitializeStatus = lv_textarea_create(ui_PowerON);
lv_obj_set_width( ui_InitializeStatus, 290);
lv_obj_set_height( ui_InitializeStatus, 70);
lv_obj_set_x( ui_InitializeStatus, 0 );
lv_obj_set_y( ui_InitializeStatus, 63 );
lv_obj_set_align( ui_InitializeStatus, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_InitializeStatus,"System Initializing...");
lv_obj_clear_flag( ui_InitializeStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
ui_object_set_themeable_style_property(ui_InitializeStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_InitializeStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_align(ui_InitializeStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InitializeStatus, &ui_font_ASCII19, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_InitializeStatus, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_InitializeStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_InitializeStatus, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_FWVersion = lv_label_create(ui_PowerON);
lv_obj_set_width( ui_FWVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FWVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FWVersion, 14 );
lv_obj_set_y( ui_FWVersion, 0 );
lv_obj_set_align( ui_FWVersion, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_FWVersion,"");
ui_object_set_themeable_style_property(ui_FWVersion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_FWVersion, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_FWVersion, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

}
