// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_POWERON_H
#define UI_POWERON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PowerON
extern void ui_PowerON_screen_init(void);
extern void ui_PowerON_screen_destroy(void);
extern lv_obj_t * ui_PowerON;
extern lv_obj_t * ui_ImagePowerON;
extern lv_obj_t * ui_InitializeStatusBar;
extern lv_obj_t * ui_InitializeStatus;
extern lv_obj_t * ui_FWVersion;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

