// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_PIDSETTINGSCREEN_H
#define UI_PIDSETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PIDSettingScreen
extern void ui_PIDSettingScreen_screen_init(void);
extern void ui_PIDSettingScreen_screen_destroy(void);
extern lv_obj_t * ui_PIDSettingScreen;
extern lv_obj_t * ui_PIDSettingHeader;
extern lv_obj_t * ui_TextPIDSettingHeader;
extern void ui_event_PIDSettingBack(lv_event_t * e);
extern lv_obj_t * ui_PIDSettingBack;
extern lv_obj_t * ui_PIDSettingDock;
extern lv_obj_t * ui_TextSolderingPID;
extern void ui_event_SolderingKP(lv_event_t * e);
extern lv_obj_t * ui_SolderingKP;
extern lv_obj_t * ui_TextPIDKP;
extern void ui_event_SolderingKI(lv_event_t * e);
extern lv_obj_t * ui_SolderingKI;
extern lv_obj_t * ui_TextPIDKI;
extern void ui_event_SolderingKD(lv_event_t * e);
extern lv_obj_t * ui_SolderingKD;
extern lv_obj_t * ui_TextPIDKD;
extern void ui_event_SolderingKPDown(lv_event_t * e);
extern lv_obj_t * ui_SolderingKPDown;
extern void ui_event_SolderingKPUp(lv_event_t * e);
extern lv_obj_t * ui_SolderingKPUp;
extern void ui_event_SolderingKIDown(lv_event_t * e);
extern lv_obj_t * ui_SolderingKIDown;
extern void ui_event_SolderingKIUp(lv_event_t * e);
extern lv_obj_t * ui_SolderingKIUp;
extern void ui_event_SolderingKDDown(lv_event_t * e);
extern lv_obj_t * ui_SolderingKDDown;
extern void ui_event_SolderingKDUp(lv_event_t * e);
extern lv_obj_t * ui_SolderingKDUp;
extern lv_obj_t * ui_TextHeatgunPID;
extern void ui_event_HeatgunKP(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKP;
extern lv_obj_t * ui_TextPIDKP2;
extern void ui_event_HeatgunKI(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKI;
extern lv_obj_t * ui_TextPIDKI2;
extern void ui_event_HeatgunKD(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKD;
extern lv_obj_t * ui_TextPIDKD2;
extern void ui_event_HeatgunKPDown(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKPDown;
extern void ui_event_HeatgunKPUp(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKPUp;
extern void ui_event_HeatgunKIDown(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKIDown;
extern void ui_event_HeatgunKIUp(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKIUp;
extern void ui_event_HeatgunKDDown(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKDDown;
extern void ui_event_HeatgunKDUp(lv_event_t * e);
extern lv_obj_t * ui_HeatgunKDUp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

