// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_SOLDERINGTEMPSETSCREEN_H
#define UI_SOLDERINGTEMPSETSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SolderingTempSetScreen
extern void ui_SolderingTempSetScreen_screen_init(void);
extern void ui_SolderingTempSetScreen_screen_destroy(void);
extern lv_obj_t * ui_SolderingTempSetScreen;
extern lv_obj_t * ui_SolderingKeyboard;
extern void ui_event_SolderingConfirm(lv_event_t * e);
extern lv_obj_t * ui_SolderingConfirm;
extern void ui_event_SolderingDelete(lv_event_t * e);
extern lv_obj_t * ui_SolderingDelete;
extern void ui_event_SolderingNum0(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum0;
extern lv_obj_t * ui_SolderingNumPanel;
extern void ui_event_SolderingNum1(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum1;
extern void ui_event_SolderingNum2(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum2;
extern void ui_event_SolderingNum3(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum3;
extern void ui_event_SolderingNum4(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum4;
extern void ui_event_SolderingNum5(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum5;
extern void ui_event_SolderingNum6(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum6;
extern void ui_event_SolderingNum7(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum7;
extern void ui_event_SolderingNum8(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum8;
extern void ui_event_SolderingNum9(lv_event_t * e);
extern lv_obj_t * ui_SolderingNum9;
extern lv_obj_t * ui_SolderingTempSetDock;
extern lv_obj_t * ui_TextSolderingTempSetting;
extern lv_obj_t * ui_SolderingTempSetting;
extern lv_obj_t * ui_SolderingSetTemp;
extern lv_obj_t * ui_TextSolderingCurrentTemp;
extern lv_obj_t * ui_SolderingCurrentTemp;
extern void ui_event_SolderingTempSetBack(lv_event_t * e);
extern lv_obj_t * ui_SolderingTempSetBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

