// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: UI

#ifndef UI_SYSTEMSETTINGSCREEN_H
#define UI_SYSTEMSETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SystemSettingScreen
extern void ui_SystemSettingScreen_screen_init(void);
extern void ui_SystemSettingScreen_screen_destroy(void);
extern lv_obj_t * ui_SystemSettingScreen;
extern lv_obj_t * ui_SystemSettingDock;
extern lv_obj_t * ui_TextSystemSetting;
extern void ui_event_SystemSettingBack(lv_event_t * e);
extern lv_obj_t * ui_SystemSettingBack;
extern lv_obj_t * ui_SystemSetting;
extern void ui_event_PIDSetting(lv_event_t * e);
extern lv_obj_t * ui_PIDSetting;
extern lv_obj_t * ui_TextPIDSetting;
extern void ui_event_SolderingMaxTemp(lv_event_t * e);
extern lv_obj_t * ui_SolderingMaxTemp;
extern lv_obj_t * ui_TextSolderingMaxTemp;
extern lv_obj_t * ui_NameSolderingMaxTemp;
extern void ui_event_SolderingMinTemp(lv_event_t * e);
extern lv_obj_t * ui_SolderingMinTemp;
extern lv_obj_t * ui_TextSolderingMinTemp;
extern lv_obj_t * ui_NameSolderingMinTemp;
extern void ui_event_SolderingStandbyTemp(lv_event_t * e);
extern lv_obj_t * ui_SolderingStandbyTemp;
extern lv_obj_t * ui_TextSolderingStandbyTemp;
extern lv_obj_t * ui_NameSolderingStandbyTemp;
extern void ui_event_SolderingStandbyTime(lv_event_t * e);
extern lv_obj_t * ui_SolderingStandbyTime;
extern lv_obj_t * ui_TextSolderingStandbyTime;
extern lv_obj_t * ui_NameSolderingStandbyTime;
extern void ui_event_SolderingPowerLimit(lv_event_t * e);
extern lv_obj_t * ui_SolderingPowerLimit;
extern lv_obj_t * ui_NameSolderingPowerLimit;
extern void ui_event_HeatgunMaxTemp(lv_event_t * e);
extern lv_obj_t * ui_HeatgunMaxTemp;
extern lv_obj_t * ui_TextHeatgunMaxTemp;
extern lv_obj_t * ui_NameHeatgunMaxTemp;
extern void ui_event_HeatgunMinTemp(lv_event_t * e);
extern lv_obj_t * ui_HeatgunMinTemp;
extern lv_obj_t * ui_TextHeatgunMinTemp;
extern lv_obj_t * ui_NameHeatgunMinTemp;
extern void ui_event_SystemBrightness(lv_event_t * e);
extern lv_obj_t * ui_SystemBrightness;
extern lv_obj_t * ui_ImageBrightness;
extern lv_obj_t * ui_TextBrightness;
extern void ui_event_SettingSave(lv_event_t * e);
extern lv_obj_t * ui_SettingSave;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

